version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:15"
      timezone: "America/Vancouver"
    open-pull-requests-limit: 5
